### ISSUE TITLE
Conversion to LDF format

### ISSUE THREAD

**Issue by aero31aero** [KamWithK/KrDictionaries#2]
I wrote a basic script for personal use to convert these to LDF format, and then use pyglossary to convert them to any format compatible with goldendict etc. Maybe you'd wanna implement that in this repo eventually, so here's the format spec and the code:

Format spec: http://www.lingoes.net/en/dictionary/dict_format.php

```js
const dict = require("./krdict_korean_english.json");
const fs = require("fs");

let ldf = `###Title: Krdict Korean English Scrapped
###Description: A scrapped dict from GitHub
###Author: Kam with K
###Email: none@none.com
###Website: https://github.com/KamWithK/KrDictionaries
###Copyright: Unsure
`;

dict.forEach((e) => {
  const headword = e.word;
  const entries = e.entries.join("\n");
  const hanja = e.hanja ? `Hanja: ${e.hanja}` : "";
  let entry = `${e.word} ${hanja} Type: ${e.grammar_type} Homonyms: ${e.homonym}

${entries}

${e.audio_url}`;
  entry = entry.trim();
  entry = entry.replaceAll("\n", "<br>");
  ldf += `\n${headword}\n${entry}\n`;
});

fs.writeFileSync("./krdict_korean_english.ldf", ldf);

```

**Comment by KamWithK** [comment]
Ah thanks for this, looks useful
I'm busy with other projects currently but I'll consider rewriting in Python and including this script in the repository
I do though believe someone else also created a script (in their own repository, not a fork) to create yomichan dictionaries from mine (there are a few dictionaries on The Moe Way discord's Korean channel)
